### ISSUE TITLE
Triplestore

### ISSUE THREAD

**Issue by KonradHoeffner** [i-artjom/hilona-docker#2]
Vorschlag von CS:

> Daran anknüpfend eine Idee für weitere vorbereitende Arbeiten: Es wäre gut, Zeit in die Datenbankinfrastruktur des Semantic MediaWiki zu investieren. Hier könnte gleich zu Beginn eine RDF-Datenbank/einen Triplestore angebunden werden. Wäre für die Performanz und komplexere Abfragen gut.

Kannst du mal gucken, was das für Vorteile und Nachteile für HI-LONa hätte und wie das geht?
Ersetzt das dann das mariadb oder ist das zusätzlich?

Mein persönlicher Favorit für Triplestores ist ja Virtuoso: https://hub.docker.com/r/openlink/virtuoso-opensource-7/

**Comment by i-artjom** [comment]
Danke, ich recherchiere!

**Comment by i-artjom** [comment]
Pros and cons of using SPARQL and RDF with SemanticMediawiki:
https://www.semantic-mediawiki.org/wiki/Help:SPARQL_und_RDF-Speicher_nutzen

There are some known issues with Virtuoso:
https://www.semantic-mediawiki.org/wiki/Help:SPARQL_und_RDF-Speicher_nutzen#Virtuoso

An alternative that is also described on this page would be 4Store.

**Comment by KonradHoeffner** [comment]
Wird erstmal ohne Triplestore gemacht, wenn nötig später hinzufügen.
